import { db } from '@/db';
import { properties } from '@/db/schema';

async function main() {
    const sampleProperties = [
        {
            title: 'Oceanfront Penthouse with Panoramic Views',
            location: 'Miami Beach, FL',
            price: '$7,200,000',
            image: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800',
            bedrooms: 4,
            bathrooms: 4,
            area: '4,500 sqft',
            type: 'Penthouse',
            featured: true,
            category: 'Luxury',
            description: 'Stunning oceanfront penthouse featuring floor-to-ceiling windows, private rooftop terrace, and breathtaking panoramic views of the Atlantic Ocean. This architectural masterpiece includes a gourmet kitchen with Italian marble countertops, spa-like bathrooms, and smart home technology throughout.',
            status: 'Active',
            createdAt: new Date('2024-01-15').toISOString(),
            updatedAt: new Date('2024-01-15').toISOString(),
        },
        {
            title: 'Modern Villa in Beverly Hills',
            location: 'Beverly Hills, CA',
            price: '$12,500,000',
            image: 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800',
            bedrooms: 6,
            bathrooms: 5,
            area: '8,000 sqft',
            type: 'Villa',
            featured: true,
            category: 'Luxury',
            description: 'Luxurious contemporary villa nestled in the heart of Beverly Hills, offering unparalleled privacy and sophistication. Features include infinity pool, wine cellar, home theater, and professionally landscaped gardens with mountain views.',
            status: 'Active',
            createdAt: new Date('2024-01-20').toISOString(),
            updatedAt: new Date('2024-02-10').toISOString(),
        },
        {
            title: 'Manhattan Luxury High-Rise Residence',
            location: 'Manhattan, NY',
            price: '$9,800,000',
            image: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800',
            bedrooms: 3,
            bathrooms: 3,
            area: '3,200 sqft',
            type: 'Penthouse',
            featured: false,
            category: 'Residential',
            description: 'Sophisticated high-rise residence in prime Manhattan location with stunning city skyline views. This exquisite apartment boasts custom finishes, chef\'s kitchen, private elevator access, and full-service concierge.',
            status: 'Pending',
            createdAt: new Date('2024-02-01').toISOString(),
            updatedAt: new Date('2024-02-25').toISOString(),
        },
        {
            title: 'Malibu Beach Estate with Private Access',
            location: 'Malibu, CA',
            price: '$15,750,000',
            image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800',
            bedrooms: 5,
            bathrooms: 5,
            area: '6,800 sqft',
            type: 'Estate',
            featured: true,
            category: 'Luxury',
            description: 'Spectacular beachfront estate with direct private beach access and unobstructed Pacific Ocean views. This architectural gem features open-concept living spaces, outdoor entertainment areas, infinity pool, and state-of-the-art home automation.',
            status: 'Active',
            createdAt: new Date('2024-01-10').toISOString(),
            updatedAt: new Date('2024-01-10').toISOString(),
        },
        {
            title: 'Aspen Mountain Luxury Chalet',
            location: 'Aspen, CO',
            price: '$11,200,000',
            image: 'https://images.unsplash.com/photo-1600607687644-aac4c3eac7f4?w=800',
            bedrooms: 5,
            bathrooms: 4,
            area: '5,500 sqft',
            type: 'Estate',
            featured: true,
            category: 'Vacation',
            description: 'Magnificent ski-in/ski-out mountain estate offering unparalleled luxury and breathtaking mountain vistas. Features include vaulted ceilings, stone fireplace, heated outdoor pool and spa, wine room, and private gym with panoramic views.',
            status: 'Active',
            createdAt: new Date('2024-02-05').toISOString(),
            updatedAt: new Date('2024-02-15').toISOString(),
        },
        {
            title: 'Contemporary Mansion with Smart Home Technology',
            location: 'Scottsdale, AZ',
            price: '$6,950,000',
            image: 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800',
            bedrooms: 5,
            bathrooms: 4,
            area: '6,200 sqft',
            type: 'Mansion',
            description: 'Ultra-modern mansion featuring cutting-edge smart home technology, resort-style pool with waterfall, outdoor kitchen, and stunning desert mountain views. This entertainer\'s paradise includes a home theater, game room, and chef\'s kitchen with top-of-the-line appliances.',
            featured: false,
            category: 'Residential',
            status: 'Active',
            createdAt: new Date('2024-01-25').toISOString(),
            updatedAt: new Date('2024-02-20').toISOString(),
        },
        {
            title: 'Lake Tahoe Waterfront Luxury Home',
            location: 'Lake Tahoe, CA',
            price: '$8,450,000',
            image: 'https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=800',
            bedrooms: 4,
            bathrooms: 3,
            area: '4,800 sqft',
            type: 'Contemporary Home',
            featured: false,
            category: 'Vacation',
            description: 'Pristine lakefront estate with private dock and boat house, offering spectacular lake and mountain views. This custom-built home features floor-to-ceiling windows, gourmet kitchen, multiple decks, and luxurious master suite with spa-like bathroom.',
            status: 'Pending',
            createdAt: new Date('2024-02-10').toISOString(),
            updatedAt: new Date('2024-03-01').toISOString(),
        },
        {
            title: 'Downtown Seattle Modern High-Rise',
            location: 'Seattle, WA',
            price: '$4,500,000',
            image: 'https://images.unsplash.com/photo-1600607686527-6fb886090705?w=800',
            bedrooms: 3,
            bathrooms: 2,
            area: '3,500 sqft',
            type: 'Penthouse',
            featured: false,
            category: 'Residential',
            description: 'Elegant penthouse in the heart of downtown Seattle with sweeping views of Puget Sound and the Olympic Mountains. Features include Italian cabinetry, marble bathrooms, private terrace, and access to exclusive building amenities including rooftop lounge and fitness center.',
            status: 'Sold',
            createdAt: new Date('2024-01-05').toISOString(),
            updatedAt: new Date('2024-02-28').toISOString(),
        },
        {
            title: 'Historic Charleston Estate with Gardens',
            location: 'Charleston, SC',
            price: '$5,800,000',
            image: 'https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800',
            bedrooms: 4,
            bathrooms: 4,
            area: '5,200 sqft',
            type: 'Estate',
            featured: false,
            category: 'Luxury',
            description: 'Meticulously restored historic estate in Charleston\'s most prestigious neighborhood, featuring original architectural details and modern luxury amenities. This stunning property includes formal gardens, carriage house, gourmet kitchen, and elegant entertaining spaces.',
            status: 'Active',
            createdAt: new Date('2024-02-15').toISOString(),
            updatedAt: new Date('2024-03-05').toISOString(),
        },
        {
            title: 'Waterfront Villa with Private Marina',
            location: 'Naples, FL',
            price: '$10,300,000',
            image: 'https://images.unsplash.com/photo-1600607686923-c7dcadaa6f17?w=800',
            bedrooms: 6,
            bathrooms: 5,
            area: '7,500 sqft',
            type: 'Villa',
            featured: false,
            category: 'Luxury',
            description: 'Extraordinary waterfront villa with private marina and deep-water boat slips, offering direct Gulf of Mexico access. This Mediterranean-inspired masterpiece features Italian tile, custom millwork, resort-style pool with spa, summer kitchen, and lush tropical landscaping.',
            status: 'Active',
            createdAt: new Date('2024-01-30').toISOString(),
            updatedAt: new Date('2024-01-30').toISOString(),
        },
    ];

    await db.insert(properties).values(sampleProperties);
    
    console.log('✅ Properties seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});